### ISSUE TITLE
using SSCMS.Restriction.Abstractions;  没有这个插件

### ISSUE THREAD

**Issue by shigophilo** [Richard-Tang/SSCMS-PluginShell#1]
其实 
using SSCMS.Restriction.Abstractions;
using SSCMS.Restriction.Core;
这两条都报错
不过可以安装SS.Restriction
但是安装完SS.Restriction,修改SSCMS.Restriction为SS.Restriction后,using SSCMS.Restriction.Abstractions;没有找到

**Comment by Richard-Tang** [comment]
> 其实 using SSCMS.Restriction.Abstractions; using SSCMS.Restriction.Core; 这两条都报错 不过可以安装SS.Restriction 但是安装完SS.Restriction,修改SSCMS.Restriction为SS.Restriction后,using SSCMS.Restriction.Abstractions;没有找到

这个插件是好久前的了，之前在实战项目中用过是有效果的，可能是后续sscms的插件有变动。但是整体getshell思路都是一样的，可以参考一下现在的sscms插件实现思路然后自己写一个进行反弹shell即可。

**Comment by Richard-Tang** [comment]
已经重新调整了
